ENTITY_STATUS_IDLE = 0
ENTITY_STATUS_WALK = 1
ENTITY_STATUS_RUN = 2
ENTITY_STATUS_PUNCH = 3
ENTITY_STATUS_FIRE = 4
ENTITY_STATUS_HURT = 5
ENTITY_STATUS_ON_GROUND = 6
ENTITY_STATUS_DEATH = 7

KEY_STATUS_RELEASED = 100
KEY_STATUS_DOWN = 101
KEY_STATUS_PRESSED = 102
KEY_STATUS_UP = 103

GAME_TYPE_OFFLINE = 200
GAME_TYPE_ONLINE = 201

GAME_STATUS_WAIT = 300
GAME_STATUS_PLAY = 301
GAME_STATUS_PAUSE = 302
GAME_STATUS_OVER = 303
